# Stage 1: Build the React app
FROM node:18-alpine AS build

WORKDIR /app

COPY . .

RUN npm install

RUN npm run build

# Stage 2: Serve build files (static files) with Nginx
FROM nginx:stable-alpine

COPY --from=build /app/dist /usr/share/nginx/html/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
