version: '3.1'

services:
  database:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    ports:
      - 5432:5432
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_HOST_AUTH_METHOD: trust
