version: '3.1'

services:
  database:
    image: postgres:latest
    container_name: database-service
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
  backend:
    build: ./backend/.
    image: backend-image
    container_name: backend-service
    restart: always
    ports:
      - 5000:5000
      - 5555:5555
    depends_on:
      - database
  frontend:
    build: ./frontend/.
    image: frontend-image
    container_name: frontend-service
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - backend