version: "3.1"

services:
  database:
    image: postgres:17-alpine3.20
    container_name: database-service
    restart: always
    env_file: "./.env"

  backend:
    build: ./backend/.
    image: backend-image
    container_name: backend-service
    restart: always
    ports:
      - 5000:5000
      - 5555:5555
      - 1337:1337
    volumes:
      - ./backend:/app
    depends_on:
      - database

  frontend:
    build: ./frontend/.
    image: frontend-image
    container_name: frontend-service
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
