# Stage 1: Build the Nest app
FROM node:18-alpine AS build

WORKDIR /app

COPY . .

RUN npm install

RUN npm run build

# Stage 2: Run Node.js production server
FROM node:18-alpine

ENV NODE_ENV=production

USER node

WORKDIR /home/node/app

COPY --from=build --chown=node:node /app/dist ./dist
COPY --from=build --chown=node:node /app/package*.json .

RUN npm install --production

EXPOSE 5000
EXPOSE 1337 

CMD ["sh", "-c", "npm run migrate:prod ; npm run start:prod"]
